extension_dir="C:\Program Files (x86)\Local\resources\extraResources\lightning-services\php-8.2.27+1\bin\win64\ext"
extension=curl
extension=fileinfo
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=zip

memory_limit=512M
upload_max_filesize=32M
post_max_size=32M
max_execution_time=120
date.timezone=Asia/Beirut
